### PR TITLE
Merge pull request #1 from kbwalex/master

### PR DESCRIPTION
**Pull request by Obi-Codez**
updated

### CODE REVIEW

**Comment by kbwalex** [comment]
Sorry bro,
I don't understand this anymore. I had done the project and I have been
trying to git push but all prove abortive.

**Comment by kbwalex** [comment]
I have finally push.

Thanks

**Comment by Obi-Codez** [comment]
Okay bro. Will check it once I’m back online.
Regards.

**Comment by kbwalex** [comment]
This is my whatsapp number 08057078606

**Pull request merged**
